#!/bin/bash

# Author: Sander van Vugt, modified by Brad Penney
# Purpose: Demonstrate read into a variable, kill a process

echo Which process do you want to kill?
read TOKILL

kill $(ps aux | grep $TOKILL | grep -v grep | awk '{ print $2 }') 2>> /tmp/scriptErrorLog

if [ $? = 0 ]
	then
		echo Killed $TOKILL
	else
		echo "Sorry, that process wasn't found on the system"
fi

exit 0
